Creating Codedeploy for that appspec.yaml | deploy/scripts file added

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -75,6 +75,17 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            if ! command -v aws &> /dev/null
+            then
+                echo "AWS CLI not found. Installing..."
+                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                unzip awscliv2.zip
+                sudo ./aws/install
+                echo "AWS CLI installed successfully."
+            else
+                echo "AWS CLI is already installed."
+            fi
+
             aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws configure set default.region ap-south-1
@@ -90,4 +101,4 @@ jobs:
 
             docker run -p 80:5000 -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} --name shashankraiCICD  222634383382.dkr.ecr.ap-south-1.amazonaws.com/emotiondetection:latest
 
-            
+            echo "Deployment complete!"
